$schema: https://raw.githubusercontent.com/remal-github-actions/sync-with-template/main/local-transformations.schema.json

repositories:
- remal-github-actions/matrix-versions

transformations:
- name: LICENSE
  includes:
  - 'LICENSE'
  format: text
  ignore: true
