/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type VersionOnlyFilter =
  | "lts"
  | "stable"
  | "stable+current-unstable"
  | "stable-majors"
  | "stable-majors+current-unstable"
  | "stable-minors"
  | "stable-minors+current-unstable"
  | "stable-patches"
  | "stable-patches+current-unstable"
  | "current-unstable";
export type VersionFilter = string;
/**
 * Dependency versioning (see https://docs.renovatebot.com/modules/versioning/)
 */
export type Versioning = StaticVersioning | string;
export type StaticVersioning =
  | "aws-eks-addon"
  | "aws-machine-image"
  | "azure-rest-api"
  | "bazel-module"
  | "cargo"
  | "composer"
  | "conan"
  | "deb"
  | "debian"
  | "devbox"
  | "docker"
  | "git"
  | "glasskube"
  | "go-mod-directive"
  | "gradle"
  | "hashicorp"
  | "helm"
  | "hex"
  | "ivy"
  | "kubernetes-api"
  | "loose"
  | "maven"
  | "node"
  | "npm"
  | "nuget"
  | "pep440"
  | "perl"
  | "poetry"
  | "pvp"
  | "python"
  | "redhat"
  | "rez"
  | "rpm"
  | "ruby"
  | "same-major"
  | "semver"
  | "semver-coerced"
  | "swift"
  | "ubuntu"
  | "unity3d";
/**
 * This interface was referenced by `undefined`'s JSON-Schema definition
 * via the `patternProperty` "^(gradle-wrapper|java|java/full|maven:.+|node|node/full)$".
 */
export type CompatibilityAlias = string;

/**
 * Config for matrix-version GitHub action
 */
export interface Config {
  /**
   * Property to dependency mappings
   */
  matrix?: {
    [k: string]: MatrixItem;
  };
  /**
   * Repository authorizations
   */
  auth?: HostAuth[];
  /**
   * Compatibilities with other dependencies
   */
  globalCompatibilities?: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^(gradle-wrapper|java|java/full|maven:.+|node|node/full)$".
     */
    [k: string]: CompatibilityItem[];
  };
  /**
   * Compatibility aliases
   */
  globalCompatibilityAliases?: {
    [k: string]: CompatibilityAlias;
  };
}
/**
 * This interface was referenced by `undefined`'s JSON-Schema definition
 * via the `patternProperty` "^[a-z]([a-zA-Z0-9._-]*[a-zA-Z0-9])?$".
 */
export interface MatrixItem {
  /**
   * Dependency ID in format of `<datasource>:<dependency>`
   */
  dependency: string;
  /**
   * Only versions match to all of these filters are included
   */
  only?: VersionOnlyFilter[];
  /**
   * Versions match to any of these filters are included
   */
  include?: VersionFilter[];
  /**
   * Versions match to any of these filters are excluded
   */
  exclude?: VersionFilter[];
  versioning?: Versioning;
  /**
   * Repository URLs
   */
  repositories?: string[];
  /**
   * Dependency compatibilities with other dependencies
   */
  compatibilities?: CompatibilityItem[];
  /**
   * Set to `true` to disable using global compatibilities for this matrix item
   */
  withoutGlobalCompatibilities?: boolean;
}
export interface CompatibilityItem {
  /**
   * Dependency version range
   */
  versionRange: string;
  /**
   * Compatibility dependency ID
   */
  dependency: string;
  /**
   * Compatibility dependency range
   */
  dependencyVersionRange: string;
}
export interface HostAuth {
  /**
   * Repository host
   */
  host: string;
  /**
   * Repository type
   */
  type?: "gradle-wrapper" | "java" | "java/full" | "maven" | "node" | "node/full";
  /**
   * Token for the repository
   */
  token?: string;
  /**
   * Username for the repository
   */
  username?: string;
  /**
   * Password for the repository
   */
  password?: string;
}
