/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Dependency versioning (see https://docs.renovatebot.com/modules/versioning/)
 */
export type Versioning = StaticVersioning | string;
export type StaticVersioning =
  | "aws-machine-image"
  | "azure-rest-api"
  | "cargo"
  | "composer"
  | "conan"
  | "deb"
  | "debian"
  | "docker"
  | "git"
  | "go-mod-directive"
  | "gradle"
  | "hashicorp"
  | "helm"
  | "hex"
  | "ivy"
  | "kubernetes-api"
  | "loose"
  | "maven"
  | "node"
  | "npm"
  | "nuget"
  | "pep440"
  | "perl"
  | "poetry"
  | "python"
  | "redhat"
  | "rez"
  | "ruby"
  | "semver"
  | "semver-coerced"
  | "swift"
  | "ubuntu";

/**
 * Config for matrix-version GitHub action
 */
export interface Config {
  /**
   * Property to dependency mappings
   */
  matrix?: {
    [k: string]: MatrixItem;
  };
  /**
   * Compatibilities with other dependencies
   */
  compatibilities?: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^(gradle-wrapper|java(:(lts|jre|jre-lts))?|maven:.+|node(:lts)?)$".
     */
    [k: string]: CompatibilityItem[];
  };
  /**
   * Repository authorizations
   */
  auth?: HostAuth[];
}
/**
 * This interface was referenced by `undefined`'s JSON-Schema definition
 * via the `patternProperty` "^[a-z]([a-zA-Z0-9._-]*[a-zA-Z0-9])?$".
 */
export interface MatrixItem {
  /**
   * Dependency ID in format of `<datasource>:<dependency>`
   */
  dependency: string;
  "static-versioning"?: Versioning;
  /**
   * Repository URL
   */
  repository?: string;
  /**
   * Dependency compatibilities with other dependencies
   */
  compatibilities?: CompatibilityItem[];
}
export interface CompatibilityItem {
  /**
   * Dependency version range
   */
  versionRange: string;
  /**
   * Compatibility dependency ID
   */
  dependency: string;
  /**
   * Compatibility dependency range
   */
  dependencyVersionRange: string;
}
export interface HostAuth {
  /**
   * Repository host
   */
  host: string;
  /**
   * Repository type
   */
  type?: "gradle-wrapper" | "java" | "maven" | "node";
  /**
   * Token for the repository
   */
  token?: string;
  /**
   * Username for the repository
   */
  username?: string;
  /**
   * Password for the repository
   */
  password?: string;
}
