/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Config for matrix-version GitHub action
 */
export interface Config {
  /**
   * Property to dependency mappings
   */
  matrix?: {
    [k: string]: MatrixItem;
  };
  /**
   * Repository authorizations
   */
  auth?: HostAuth[];
}
/**
 * This interface was referenced by `undefined`'s JSON-Schema definition
 * via the `patternProperty` "^[a-z]([a-zA-Z0-9._-]*[a-zA-Z0-9])?$".
 */
export interface MatrixItem {
  /**
   * Dependency ID in format of `<datasource>:<dependency>`
   */
  dependency: string;
  /**
   * Dependency versioning (see https://docs.renovatebot.com/modules/versioning/)
   */
  versioning?:
    | "aws-machine-image"
    | "azure-rest-api"
    | "cargo"
    | "composer"
    | "conan"
    | "deb"
    | "debian"
    | "docker"
    | "git"
    | "go-mod-directive"
    | "gradle"
    | "hashicorp"
    | "helm"
    | "hermit"
    | "hex"
    | "ivy"
    | "kubernetes-api"
    | "loose"
    | "maven"
    | "nixpkgs"
    | "node"
    | "npm"
    | "nuget"
    | "pep440"
    | "perl"
    | "poetry"
    | "python"
    | "redhat"
    | "regex"
    | "rez"
    | "ruby"
    | "semver"
    | "semver-coerced"
    | "swift"
    | "ubuntu";
  /**
   * Repository URL
   */
  repository?: string;
  /**
   * Compatibilities with other dependencies
   */
  compatibilities?: CompatibilityItem[];
}
export interface CompatibilityItem {
  /**
   * Dependency ID
   */
  dependency: string;
  /**
   * Version range
   */
  versionRange: string;
}
export interface HostAuth {
  /**
   * Repository host
   */
  host: string;
  /**
   * Repository type
   */
  type?:
    | "artifactory"
    | "aws-machine-image"
    | "aws-rds"
    | "azure-bicep-resource"
    | "azure-pipelines-tasks"
    | "bitbucket-tags"
    | "cdnjs"
    | "clojure"
    | "conan"
    | "conda"
    | "cpan"
    | "crate"
    | "dart"
    | "dart-version"
    | "deno"
    | "docker"
    | "dotnet-version"
    | "flutter-version"
    | "galaxy"
    | "galaxy-collection"
    | "git-refs"
    | "git-tags"
    | "github-release-attachments"
    | "github-releases"
    | "github-tags"
    | "gitlab-packages"
    | "gitlab-releases"
    | "gitlab-tags"
    | "go"
    | "golang-version"
    | "gradle-version"
    | "helm"
    | "hermit"
    | "hex"
    | "hexpm-bob"
    | "java-version"
    | "jenkins-plugins"
    | "kubernetes-api"
    | "maven"
    | "node"
    | "npm"
    | "nuget"
    | "orb"
    | "packagist"
    | "pod"
    | "puppet-forge"
    | "pypi"
    | "repology"
    | "ruby-version"
    | "rubygems"
    | "sbt-package"
    | "sbt-plugin"
    | "terraform-module"
    | "terraform-provider";
  /**
   * Token for the repository
   */
  token?: string;
  /**
   * Username for the repository
   */
  username?: string;
  /**
   * Password for the repository
   */
  password?: string;
}
